name: generate-doi

on:
    schedule:
        - cron: '0 0 * * 0' # Every Sunday at midnight
    workflow_dispatch:

jobs:
    get-updated-apps:
        runs-on: ubuntu-22.04
        outputs:
            app_batches: ${{ steps.list_apps.outputs.app_batches }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Check for apps to publish to Zenodo
              id: list_apps
              run: |
                # Get the list of unpublished images from app.json
                echo "Fetching apps list from GitHub registry..."
                export APP_BATCHES=$(python .github/workflows/get-unpublished-apps.py --zenodo_token ${{ secrets.ZENODO_TOKEN }})
                echo "app_batches=${APP_BATCHES}" >> $GITHUB_OUTPUT

    publish-doi:
      needs: get-updated-apps
      runs-on: ubuntu-22.04
      if: ${{ needs.get-updated-apps.outputs.app_batches != '[]' }}
      strategy:
          fail-fast: false
          matrix:
            app_batches: ${{ fromJSON(needs.get-updated-apps.outputs.app_batches) }}
      steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name : Publish singularity files in batch
            shell: bash
            run: |
              echo "Processing batches: ${{ matrix.app_batches }}"
              for app in $(echo ${{ matrix.app_batches }} | jq -r '.[]'); do
                echo "  Processing app: $app"
                export IMAGE_HOME="/home/runner"
                curl --output "$IMAGE_HOME/${app}.simg" "https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/neurodesk/${app}.simg"
                echo "Upload container $IMAGE_HOME/${app}.simg to Zenodo"
                echo $(find $IMAGE_HOME/${app}.simg)
                export DOI_URL=$(python3 .github/workflows/publish-doi.py --container_filepath="$IMAGE_HOME/${app}.simg" --container_name=${app} --token=${{ secrets.ZENODO_TOKEN }})
                echo "DOI_URL: $DOI_URL"
              done
